---
title: "Watershed Flow:Ecology Summary"
output: word_document
---

```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,results='hide'}

rm(list = ls())  #clear variables
options(timeout=2400); # set timeout to twice default level to avoid abort due to high traffic

library(quantreg);
library(ggplot2);
library(ggrepel);
library(ggpmisc);
library(grid);
library(httr);
library(data.table);
library(scales);
library(relimp, pos=28);
#----------------------------------------------
site <- "http://deq2.bse.vt.edu/d.dh"    #Specify the site of interest, either d.bet OR d.dh
datasite <- "http://deq2.bse.vt.edu/d.dh"    #Specify the site of interest, either d.bet OR d.dh
#----------------------------------------------
#----FOR RUNNING LOCALLY:
# Only need to change 1 path here - set to wherever this code is located
basepath='/var/www/R';

# set your local directory paths in config.local.private located in filepath above
# this file will NOT be sent to git, so it should persist
# so, edit config.local.private once and you should be good to go
source(paste(basepath,'config.local.private',sep='/'));
# all these rely on variables set in config.local.private
source(paste(hydro_tools,"VAHydro-2.0/rest_functions.R", sep = "/")); 
source(paste(hydro_tools,"auth.private", sep = "/"));#load rest username and password, contained in auth.private file
source(paste(fxn_locations,"elf_quantreg.R", sep = ""));
source(paste(fxn_locations,"elf_pct_chg.R", sep = ""));
source(paste(fxn_locations,"elf_pw_it.R", sep = ""));
source(paste(fxn_locations,"elf_ymax.R", sep = ""));
source(paste(fxn_locations,"elf_assemble_batch.R", sep = ""));

token <- rest_token(site, token, rest_uname, rest_pw);

# Load Default inputs
source(paste(fxn_locations,"elf_default_inputs.R", sep = ""));
#####
inputs$x_metric = 'erom_q0001e_mean'; #Flow metric to be plotted on the x-axis
inputs$y_metric = 'aqbio_nt_total';
inputs$ws_ftype = 'nhd_huc10';
inputs$bundle = 'watershed';
inputs$target_hydrocode = '0208020103';
inputs$quantile = 0.50;
inputs$send_to_rest = "NO";
inputs$sampres = 'species';
inputs$glo = 1;
inputs$ghi = 530;
inputs$method = "quantreg"; #quantreg, pwit, ymax, twopoint, pwit_RS
inputs$dataset_tag = 'bpj-530';
inputs$token = token;


##### Data Acquisition #####
#retrieve raw data
mydata <- vahydro_fe_data(
  inputs$target_hydrocode, inputs$x_metric, inputs$y_metric, 
  inputs$bundle, inputs$ws_ftype, inputs$sampres
);
data <- elf_cleandata(mydata, inputs);
# do ymax calcs and plot
#elf_ymax(
#  inputs, data, x_metric_code = "erom_q0001e_mean", 
#  y_metric_code = "aqbio_nt_total", ws_ftype_code = 'landunit', 
#  Feature.Name_code = 'Virginia', Hydroid_code = 'usa_state_virginia', 
#  search_code = 'usa_state_virginia', token, 
#  startdate = min(data$tstime), enddate = max(data$tstime))

feature <- getFeature(
  list(
    ftype = inputs$ws_ftype,
    bundle = inputs$bundle,
    hydrocode = inputs$target_hydrocode
  )
  , token, base_url);


#perform quantile regression calculation and plot 
qrp <- elf_quantreg(
 inputs, data, x_metric_code = inputs$x_metric, 
 y_metric_code = inputs$y_metric, 
 ws_ftype_code = NULL, 
 Feature.Name_code = feature$name, 
 Hydroid_code = inputs$target_hydrocode, 
 search_code = NULL, token, 
 min(data$tstime), max(data$tstime), geom=feature$geom
)

#perform quantile regression calculation and plot 
#elf_ymax(
#  inputs, data, x_metric_code = inputs$x_metric, 
#  y_metric_code = inputs$y_metric, 
#  ws_ftype_code = NULL, 
#  Feature.Name_code = 'Virginia', 
#  Hydroid_code = inputs$target_hydrocode, 
#  search_code = NULL, token, 
#  min(data$tstime), max(data$tstime), geom=feature$geom
#)
```

```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,fig.width=8,fig.height=8}
qrp

#plot(log(data$x_value), data$y_value)
#reg <- lm(y_value~log(x_value),data)
#abline(lm(y_value~log(x_value),data))
#lines(log(data$x_value[order(data$x_value)]), #loess(y_value~log(x_value),data)$fitted[order(data$x_value)],col="blue",lwd=3)
#lines(table$x[order(table$x)],(loess(as.character(pct_chg_10) ~ #x,data=table))$fitted[order(table$x)],col="blue",lwd=3)
#summary(reg)

#ndata <- subset(data, x_value < 100.0)
#plot(ndata$x_value, ndata$y_value)
#reg <- lm(y_value~x_value,ndata)
#abline(lm(y_value~x_value,ndata))
#summary(reg)



##### Plot PWIT ####
#for setting ghi = max x_value
#inputs$ghi <- max(mydata$x_value);
# modify elf_pwit to do analysis and return results
#inputs$glo = 100;
#inputs$ghi = 200;
#elf_pw_it (
#  inputs, data, inputs$x_metric, 
#  inputs$y_metric, ws_ftype_code = NULL, 
#  feature$name, feature$name, 
#  feature$name, token, 
#  min(data$tstime), max(data$tstime), geom=feature$geom
#)
# add new function
# plot_elf_pwit()
# add new function store_elf_pwit() (if SEND_TO_REST = TRUE)

# Regression Diagnostics here
upper.quant = elf_upper(data, inputs$quantile)
upper.quant$lnx = log(upper.quant$x_value)
regupper = lm(y_value ~ lnx,data = upper.quant)
summary(regupper)
oldpar <- par(oma=c(0,0,3,0), mfrow=c(2,2))
plot(regupper)
par(oldpar)

shapiro.test(residuals (regupper))

#influence stats
inflm.ELF <- influence.measures(regupper)
which(apply(inflm.ELF$is.inf, 1, any))   #identifies the points that are influence points
summary(inflm.ELF) # only these

```
==Filter Out Selected Leverage Points==
```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,fig.width=8,fig.height=8}
# filter out stations
#perform quantile regression calculation and plot 
data = subset(data, hydrocode != 'DGIF041253')
qrp <- elf_quantreg(
 inputs, data, x_metric_code = inputs$x_metric, 
 y_metric_code = inputs$y_metric, 
 ws_ftype_code = NULL, 
 Feature.Name_code = feature$name, 
 Hydroid_code = inputs$target_hydrocode, 
 search_code = NULL, token, 
 min(data$tstime), max(data$tstime), geom=feature$geom
)
qrp
upper.quant = subset(upper.quant, hydrocode != 'DGIF041253')
upper.quant$lnx = log(upper.quant$x_value)
regupper = lm(y_value ~ lnx,data = upper.quant)
summary(regupper)
oldpar <- par(oma=c(0,0,3,0), mfrow=c(2,2))
plot(regupper)
par(oldpar)

shapiro.test(residuals (regupper))

#influence stats
inflm.ELF <- influence.measures(regupper)
which(apply(inflm.ELF$is.inf, 1, any))   #identifies the points that are influence points
summary(inflm.ELF) # only these

#pander(wshed_summary_tbl, split.table=Inf);
```
