---
title: "ELF Monthly Comparisons"
output: word_document
---

```{r, echo=FALSE}
# install.packages('gdata')
options(timeout=2000);
library('gdata')
source("/var/www/R/config.local.private");
source(paste(base_directory,"Analysis/query_elf_statistics.R", sep = "/")); 


plot_monthly <- function (data, subname = 'all', metric = "out_rsq_adj", ymin = 0.5, ymax = 1.0) {
  # dataset_tag: bpj-530, bpj-rcc
  data.da <- subset(data, in_xvar == 'nhdp_drainage_sqmi');
  data.mean <- subset(data, in_xvar == 'erom_q0001e_mean');
  data.jan <- subset(data, in_xvar == 'erom_q0001e_jan');
  data.feb <- subset(data, in_xvar == 'erom_q0001e_feb');
  data.mar <- subset(data, in_xvar == 'erom_q0001e_mar');
  data.apr <- subset(data, in_xvar == 'erom_q0001e_apr');
  data.may <- subset(data, in_xvar == 'erom_q0001e_may');
  data.jun <- subset(data, in_xvar == 'erom_q0001e_june');
  data.jul <- subset(data, in_xvar == 'erom_q0001e_july');
  data.aug <- subset(data, in_xvar == 'erom_q0001e_aug');
  data.sep <- subset(data, in_xvar == 'erom_q0001e_sept');
  data.oct <- subset(data, in_xvar == 'erom_q0001e_oct');
  data.nov <- subset(data, in_xvar == 'erom_q0001e_nov');
  data.dec <- subset(data, in_xvar == 'erom_q0001e_dec');
  n = c('DA', 'Mean', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')
  title <- paste(ftype, " Q=", 100.*(1.0 - quantile), "%", subname, "for \n", metric, " = f(DA), Qmean,.., Qdec");
  if (length(data.da$s_adminid) > 1) {
    ns <- cbind(
       'DA' = length(data.da[,metric]), 
       'Qmean' = length(data.mean[,metric]), 
       'Qjan' = length(data.jan[,metric]), 
       'Qfeb' = length(data.feb[,metric]),  
       'Qmar' = length(data.mar[,metric]),  
       'Qapr' = length(data.apr[,metric]),  
       'Qmay' = length(data.may[,metric]),  
       'Qjun' = length(data.jun[,metric]),  
       'Qjul' = length(data.jul[,metric]),  
       'Qaug' = length(data.aug[,metric]), 
       'Qsep' = length(data.sep[,metric]),  
       'Qoct' = length(data.oct[,metric]),  
       'Qnov' = length(data.nov[,metric]),  
       'Qdec' = length(data.dec[,metric])
    )
    boxplot(
      data.da[,metric], data.mean[,metric], data.jan[,metric], data.feb[,metric], data.mar[,metric], 
        data.apr[,metric], data.may[,metric], data.jun[,metric], data.jul[,metric], data.aug[,metric], 
        data.sep[,metric], data.oct[,metric], data.nov[,metric], data.dec[,metric],
      names = n, 
      main = title,
      ylim = c(ymin, ymax)
    );
    
    # this is an example of labelling the bars with the n's
    #b <- boxplot(xvar ~ f1, data=frame, plot=0)
    #text(1:length(b$n), b$stats[5,]+1, paste("n=", b$n))
    #boxplot(xvar ~ f1, data=frame, xlab="input values", names=paste(b$names, "(n=", b$n, ")"))
    barplot(ns, names.arg=n, main=paste("# of Sig. Relationships", subname), 
            xlab="DA/Flow Variable")
  } else {
    # we are running a single watershed, so use a bar chart
    nms = strsplit(as.vector(data$in_xvar), '_', fixed = TRUE);
    xs = matrix(unlist(nms),ncol=3,byrow=TRUE)
    labs = xs[,3]
    par(las=1) # make label text perpendicular to axis
    barplot(data[,metric], names.arg=labs, main=paste("R# for region", selected), 
            xlab="DA/Flow Variable",)
    
  }
}


bundle <- 'ecoregion'; # ecoregion, landunit, watershed
ftype <- 'ecoregion_iii'; # ecoregion_iii, nhd_huc6, nhd_huc6=8, nhd_huc10
metric <- 'aqbio_nt_total'; # aqbio_nt_total, aqbio_nt_cent, aqbio_nt_darter, aqbio_nt_benins
q_ftype <- "fe_quantreg";
dataset_tag = 'bpj-530'; # bpj-530, bpj-rcc, 'HUC8_quantregwHuc6bp' (huc 6)
analysis_timespan = "full";
sampres = "species";
selected <- 'all'; # all or hydrocode
quantile <- 0.8;
pmax = 0.01;
Rmin = 0.25;
stat_quantreg_glo <- 0; 
stat_quantreg_ghi <- 530; 
# ftype = fe_quantreg, fe_quantreg_pwit, fe_quantreg_ymax, fe_twopoint
# analysis_timespan = full, 1990-2010, 1970-1980, ...
# this is BS - save_directory should be fixed
save_directory = paste(file_directory,"/",sep='');
rawdata = fn_dh_elfstats (
    ftype = q_ftype,
    site = base_url,
    analysis_timespan = analysis_timespan,
    yvar = metric,
    sampres = sampres, # e.g. species, e.
    stat_quantreg_qu = quantile, # upper quantile to use
    feature_ftype = ftype,
    #stat_quantreg_ghi = stat_quantreg_ghi, #
    #stat_quantreg_glo = stat_quantreg_glo, # use 1 for pwit, 0 for quantreg
    dataset_tag = dataset_tag
);


nsall <- cbind(
 'DA' = nrow(subset(rawdata, in_xvar == 'nhdp_drainage_sqmi')),
 'Qmean' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_mean')),
 'Qjan' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_jan')),
 'Qfeb' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_feb')),
 'Qmar' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_mar')),
 'Qapr' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_apr')),
 'Qmay' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_may')),
 'Qjun' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_june')),
 'Qjul' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_july')),
 'Qaug' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_aug')),
 'Qsep' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_sept')),
 'Qoct' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_oct')),
 'Qnov' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_nov')),
 'Qdec' = nrow(subset(rawdata, in_xvar == 'erom_q0001e_dec'))
);

# filter our data?
data = rawdata; # make a copy to start so we can compare raw to filtered if desired
#data = subset(data, out_n >= 20)
#data = subset(data, out_m > 0)
data = subset(data, out_p < pmax); # 
data = subset(data, out_rsq_adj > Rmin)
#data = subset(data, isheadwater > 0)
# render it
ymin = 0.0; # restrain plot
labeltext = paste('( p<', pmax, 'R>', Rmin,' )',sep='')
plot_monthly(data, labeltext, metric = 'out_rsq_adj', ymin=ymin);
mmax = ceiling(max(data$out_m))
plot_monthly(data, labeltext, metric = 'out_m', ymin=0, ymax=mmax);

# filter our data?
data = rawdata; # make a copy to start so we can compare raw to filtered if desired
#data = subset(data, out_n >= 20)
#data = subset(data, out_m > 0)
data = subset(data, out_p < pmax); # 
data = subset(data, out_rsq_adj > Rmin)
data = subset(data, isheadwater > 0)
labeltext = paste('( headwaters, p<', pmax, 'R>', Rmin,' )',sep='')
plot_monthly(data,labeltext, ymin=ymin);

```
* Location: `r selected`
* quantile: `r quantile`
* Metric: `r metric`
* Geospatial Unit: `r ftype`
* Analysis Type: `r q_ftype`
* Timespan: `r analysis_timespan`
```{r, echo=FALSE,fig.width=3, fig.show='hold'}
cs = c( 'sqmi', 'mean', 'jan', 'feb', 'mar', 'apr', 'may', 'june', 'july', 'aug', 'sept', 'oct', 'nov', 'dec');
data.da <- subset(data, in_xvar == 'nhdp_drainage_sqmi');
# coloring bar plots: https://stackoverflow.com/questions/16121903/r-barplot-y-axis-scale-too-short
for (i in 1:nrow(data.da)) {
  hc = as.character(data.da$containing_hydrocode[i])
  data.hc = subset(data, containing_hydrocode == hc & in_xvar != 'nhdp_drainage_sqkm')
  data.sorted = c(
    subset(data.hc, in_xvar == 'nhdp_drainage_sqmi')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_mean')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_jan')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_feb')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_mar')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_apr')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_may')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_jun')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_jul')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_aug')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_sep')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_oct')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_nov')$out_rsq_adj,
    subset(data.hc, in_xvar == 'erom_q0001e_dec')$out_rsq_adj
  )
  # try to create formatted names from variable abbreviations
  nms = strsplit(as.vector(data.hc$in_xvar), '_', fixed = TRUE);
  xs = matrix(unlist(nms),ncol=3,byrow=TRUE);
  labs = xs[,3]
  labs = subset(labs[match(cs,labs)], labs[match(cs,labs)] != 'NA')
  par(las=2) # make label text perpendicular to axis
  barplot(data.hc$out_rsq_adj, names.arg=labs, main=paste("R# ", hc), 
          xlab="DA/Flow Variable", ylim=c(0,1.0))
}
```