---
  title: "ELF Monthly Comparisons"
output: word_document
---
  #Simulated range and variability of percent loss of taxa for different biometrics
  
  
```{r, echo=FALSE}
# install.packages('gdata')
options(timeout=2000);
library('gdata')
library(pander);
source("/var/www/R/config.local.private");
source(paste(base_directory,"Analysis/query_elf_statistics.R", sep = "/")); 
source(paste(base_directory,"Analysis/plot_elf_statistics.R", sep = "/")); 
base_url <- 'http://deq2.bse.vt.edu/d.dh'

# vars
yvar = 'aqbio_benthic_nt_total';#aqbio_nt_total, aqbio_nt_cent, aqbio_nt_darter, aqbio_nt_benins, aqbio_nt_minnow
plot_title = 'NT Total Benthic';
quant = 0.8
ftype = 'nhd_huc6';
aftype = 'fe_elf';
dataset_tag = 'benthic-bpj-200';
sampres = "maj_fam_gen_spec";
rawdata = 
  fn_dh_elfstats ( ftype = aftype, 
    site = base_url, analysis_timespan = "full", yvar = yvar,
    sampres = sampres, stat_quantreg_qu = quant, feature_ftype = ftype, stat_quantreg_ghi = 'all', 
    stat_quantreg_glo = 'all', dataset_tag = dataset_tag
  );
anova_data = rawdata;
anova_data = subset(anova_data, out_m > 0)
anova_data = subset(anova_data, out_rsq_adj > 0)
anova_data = subset(anova_data, out_p <= 0.01)

fit <- aov(out_rsq_adj ~ containing_hydrocode, data=anova_data)

pander(ss)
```
```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

ss = data.frame(
  "x-Variable" = character(), 
  "0%" =  numeric(), 
  "25%" =  numeric(), 
  "50%" =  numeric(), 
  "75%" =  numeric(), 
  "100%" =  numeric(),
  "p~DA" = numeric(),
  stringsAsFactors = FALSE
) ;
dad = subset(anova_data, in_xvar == 'nhdp_drainage_sqmi');
for(i in erom_vars) {
  dset = subset(anova_data, in_xvar == i)
  qq = quantile(dset$out_rsq_adj)
  
  # could also do
  #ttq = t.test(dad$out_rsq_adj, dset$out_rsq_adj)
  ttq = wilcox.test(dad$out_rsq_adj, dset$out_rsq_adj)
  
  daq = subset(anova_data, in_xvar == 'nhdp_drainage_sqmi' | in_xvar == 'erom_q0001e_mean')

  ss <- rbind(
    ss,
    data.frame(
      "x-Variable" = i,  
      "0%" = as.numeric(qq["0%"]), 
      "25%" = as.numeric(qq["25%"]), 
      "50%" = as.numeric(qq["50%"]), 
      "75%" = as.numeric(qq["75%"]), 
      "100%" = as.numeric(qq["100%"]),
      "p~DA" = as.numeric(ttq$p.value)
    )
  )
}
names(ss) <- c("x-Variable", "0%", "25%", "50%", "75%", "100%", "p~DA")

pander(ss)
```