---
title: "ELF Monthly Comparisons"
output: word_document
---
#Simulated range and variability of percent loss of taxa for different biometrics


```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}
# install.packages('gdata')
options(timeout=2000);
library('gdata')
library(pander);
source("/var/www/R/config.local.private");
source(paste(base_directory,"Analysis/query_elf_statistics.R", sep = "/")); 
source(paste(base_directory,"Analysis/plot_elf_statistics.R", sep = "/")); 
base_url <- 'http://deq2.bse.vt.edu/d.dh'


metric <- 'aqbio_nt_total'; # aqbio_nt_total, aqbio_nt_cent, aqbio_nt_darter, aqbio_nt_benins
q_ftype <- "fe_quantreg";
dataset_tag = 'bpj-530'; # bpj-530, bpj-rcc, 'HUC8_quantregwHuc6bp' (huc 6)
analysis_timespan = "full";
sampres = "species";
selected <- 'all'; # all or hydrocode
quantile <- 0.8;
pmax = 0.01;
Rmin = 0.0;
#stat_quantreg_glo <- 0; 
#stat_quantreg_ghi <- 530; 
# ftype = fe_quantreg, fe_quantreg_pwit, fe_quantreg_ymax, fe_twopoint
# analysis_timespan = full, 1990-2010, 1970-1980, ...
# this is BS - save_directory should be fixed
save_directory = paste(file_directory,"/",sep='');
# Huc6Ghi_72=Glo ->
# bundle - ecoregion, landunit, watershed
# ftype - ecoregion_iii, nhd_huc6, nhd_huc6=8, nhd_huc10

# recreation of BPJ-rcc with all Drainage area?
batch <- data.frame(
    bundle = 'watershed', ftype = 'nhd_huc6', dataset_tag = 'bpj-huc6-rcc', q_ftype = 'fe_elf', metric = 'aqbio_nt_total', title = "HUC6 - Total # of Taxa")

# darter
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc6', dataset_tag = 'bpj-huc6-rcc', q_ftype = 'fe_elf', metric = 'aqbio_nt_darter', title = "HUC6 - # of Taxa Darters")
)

# bpj-rcc
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc6', dataset_tag = 'bpj-huc6-rcc', q_ftype = 'fe_elf', metric = 'aqbio_nt_minnow', title = "HUC6 - # of Taxa True Minnows")
)

# Using 75% value from ymax analysis of all HUC8s
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc6', dataset_tag = 'bpj-huc6-rcc', q_ftype = 'fe_elf', metric = 'aqbio_nt_cent', title = "HUC6 - # of Taxa Centrarchids")
)

# Using 75% value from ymax analysis of all HUC8s
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc6', dataset_tag = 'bpj-huc6-rcc', q_ftype = 'fe_elf', metric = 'aqbio_nt_benins', title = "HUC6 - # of Taxa Benthic Insectivores")
)

# Using 75% value from ymax analysis of all HUC8s
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc6', dataset_tag = 'bpj-huc6-rcc', q_ftype = 'fe_elf', metric = 'aqbio_nt_cypr_native', title = "HUC6 - # of Taxa Native Cyprinidae")
)

# plots box-whisker and bar charts of R2 for each month/flow/da, returns summary
ss = elf_monthly_batch_summary(batch)

```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}

pander(ss, table.split.table=Inf);

```
