---
title: "ELF Monthly Comparisons"
output: word_document
---
#Simulated range and variability of percent loss of taxa for different biometrics


```{r, echo=FALSE}
# install.packages('gdata')
options(timeout=2000);
library('gdata')
library(pander);
source("/var/www/R/config.local.private");
source(paste(base_directory,"Analysis/query_elf_statistics.R", sep = "/")); 
source(paste(base_directory,"Analysis/plot_elf_statistics.R", sep = "/")); 
base_url <- 'http://deq2.bse.vt.edu/d.dh'


# this is BS - save_directory should be fixed
save_directory = paste(file_directory,"/",sep='');

pmax = 0.01;
Rmin = 0.0;
# NT Total
batch <- data.frame(
    bundle = 'watershed', ftype = 'nhd_huc10', dataset_tag = 'bpj-530', q_ftype = 'fe_elf', metric = 'aqbio_nt_total', title = "HUC10 - Total # of Taxa")

# Minnows
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc10', dataset_tag = 'bpj-530', q_ftype = 'fe_elf', metric = 'aqbio_nt_minnow', title = "HUC10 - # of Taxa True Minnows")
)

# Centrarchids
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc10', dataset_tag = 'bpj-530', q_ftype = 'fe_elf', metric = 'aqbio_nt_cent', title = "HUC10 - # of Taxa Centrarchids")
)

# Using 75% value from ymax analysis of all HUC10s
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc10', dataset_tag = 'bpj-530', q_ftype = 'fe_quantreg', metric = 'aqbio_nt_benins', title = "HUC10 - # of Taxa Benthic Insectivores")
)

# darter
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc10', dataset_tag = 'bpj-530', q_ftype = 'fe_quantreg', metric = 'aqbio_nt_darter', title = "HUC10 - # of Taxa Darters")
)

# darter
batch <- rbind(
  batch, data.frame(
    bundle = 'watershed', ftype = 'nhd_huc10', dataset_tag = 'bpj-530', q_ftype = 'fe_elf', metric = 'aqbio_nt_cypr_native', title = "HUC10 - # of Taxa Native Cyprinidae")
)

ss = elf_monthly_batch_summary(batch)

```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}
pander(ss, table.split.table=Inf);

```
